services:
  upload_service:
    build:
      context: .
      dockerfile: Dockerfile.upload_service
    container_name: upload_service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_QUEUE: video.uploaded
    volumes:
      - ./data:/app/data

  audio_extractor_service:
    build:
      context: .
      dockerfile: Dockerfile.audio_extractor
    container_name: audio_extractor_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_QUEUE: video.uploaded
      AUDIO_OUTPUT_BASE_DIR: /app/data/audio
      AUDIO_EXTRACTED_QUEUE: audio.extracted
    volumes:
      - ./data:/app/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
