services:
  upload_service:
    build:
      context: .
      dockerfile: Dockerfile.upload_service
    container_name: upload_service
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_QUEUE: video.uploaded
    volumes:
      - ./data:/app/data

  audio_extractor_service:
    build:
      context: .
      dockerfile: Dockerfile.audio_extractor
    container_name: audio_extractor_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_QUEUE: video.uploaded
      AUDIO_OUTPUT_BASE_DIR: /app/data/audio
      AUDIO_EXTRACTED_QUEUE: audio.extracted
    volumes:
      - ./data:/app/data

  transcription_service:
    build:
      context: .
      dockerfile: Dockerfile.transcription_service
    container_name: transcription_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      AUDIO_EXTRACTED_QUEUE: audio.extracted
      TRANSCRIPT_CREATED_QUEUE: transcript.created
      TRANSCRIPT_OUTPUT_BASE_DIR: /app/data/transcripts
    volumes:
      - ./data:/app/data

  analysis_service:
    build:
      context: .
      dockerfile: Dockerfile.analysis_service
    container_name: analysis_service
    depends_on:
      - rabbitmq
      - mongo
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      TRANSCRIPT_CREATED_QUEUE: transcript.created
      ANALYSIS_COMPLETED_QUEUE: analysis.completed
      MONGO_URI: mongodb://mongo:27017/
      MONGO_DB_NAME: therapy_analysis
    volumes:
      - ./data:/app/data


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"

